name: Test & depoloy

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install poetry
        run: |
          rm -rf /home/runner/.cache/pypoetry/virtualenvs/elon-tweets-26UrJ_qR-py3.8/
          pip install poetry
          poetry install
          poetry export -f requirements.txt --without-hashes > elon_tweets/requirements.txt
        artefacts:
          elon_tweets/requirements.txt


      - name: Run tests
        run: poetry run pytest
      
      
      - name: Run type checking
        run: poetry run mypy elon_tweets
        
      
      - name: Reformat code
        run: poetry run black .


      - name: Deploy API
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{  secrets.GCP_CREDENTIALS  }}
          promote: true
          deliverables: "elon_tweets/app.yaml"

